using System;
using System.Xml.Serialization;

namespace NPOI.OpenXmlFormats.Shared
{
	[Serializable]
	[XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/math", IncludeInSchema = false)]
	public enum ItemsChoiceType8
	{
		acc,
		bar,
		borderBox,
		box,
		d,
		eqArr,
		f,
		func,
		groupChr,
		limLow,
		limUpp,
		m,
		nary,
		oMath,
		oMathPara,
		phant,
		r,
		rad,
		sPre,
		sSub,
		sSubSup,
		sSup,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkEnd")]
		bookmarkEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:bookmarkStart")]
		bookmarkStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeEnd")]
		commentRangeEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentRangeStart")]
		commentRangeStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeEnd")]
		customXmlDelRangeEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlDelRangeStart")]
		customXmlDelRangeStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeEnd")]
		customXmlInsRangeEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlInsRangeStart")]
		customXmlInsRangeStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeEnd")]
		customXmlMoveFromRangeEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveFromRangeStart")]
		customXmlMoveFromRangeStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeEnd")]
		customXmlMoveToRangeEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:customXmlMoveToRangeStart")]
		customXmlMoveToRangeStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:del")]
		del,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:ins")]
		ins,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFrom")]
		moveFrom,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeEnd")]
		moveFromRangeEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveFromRangeStart")]
		moveFromRangeStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveTo")]
		moveTo,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeEnd")]
		moveToRangeEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:moveToRangeStart")]
		moveToRangeStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:permEnd")]
		permEnd,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:permStart")]
		permStart,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:proofErr")]
		proofErr
	}
}
