using System;
using System.Xml.Serialization;

namespace NPOI.OpenXmlFormats.Shared
{
	[Serializable]
	[XmlType(Namespace = "http://schemas.openxmlformats.org/officeDocument/2006/math", IncludeInSchema = false)]
	public enum ItemsChoiceType6
	{
		t,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:annotationRef")]
		annotationRef,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:br")]
		br,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:commentReference")]
		commentReference,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:continuationSeparator")]
		continuationSeparator,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:cr")]
		cr,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:dayLong")]
		dayLong,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:dayShort")]
		dayShort,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:delInstrText")]
		delInstrText,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:delText")]
		delText,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:drawing")]
		drawing,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:endnoteRef")]
		endnoteRef,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:endnoteReference")]
		endnoteReference,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:fldChar")]
		fldChar,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:footnoteRef")]
		footnoteRef,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:footnoteReference")]
		footnoteReference,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:instrText")]
		instrText,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:lastRenderedPageBreak")]
		lastRenderedPageBreak,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:monthLong")]
		monthLong,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:monthShort")]
		monthShort,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:noBreakHyphen")]
		noBreakHyphen,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:object")]
		@object,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:pgNum")]
		pgNum,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:pict")]
		pict,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:ptab")]
		ptab,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:ruby")]
		ruby,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:separator")]
		separator,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:softHyphen")]
		softHyphen,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:sym")]
		sym,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:t")]
		t1,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:tab")]
		tab,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:yearLong")]
		yearLong,
		[XmlEnum("http://schemas.openxmlformats.org/wordprocessingml/2006/main:yearShort")]
		yearShort
	}
}
