using System;
using System.Xml.Serialization;

namespace NPOI.OpenXmlFormats.Wordprocessing
{
	[Serializable]
	[XmlType(Namespace = "http://schemas.openxmlformats.org/wordprocessingml/2006/main", IncludeInSchema = false)]
	public enum ItemsChoiceType6
	{
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:acc")]
		acc,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:bar")]
		bar,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:borderBox")]
		borderBox,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:box")]
		box,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:d")]
		d,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:eqArr")]
		eqArr,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:f")]
		f,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:func")]
		func,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:groupChr")]
		groupChr,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:limLow")]
		limLow,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:limUpp")]
		limUpp,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:m")]
		m,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:nary")]
		nary,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:oMath")]
		oMath,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:oMathPara")]
		oMathPara,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:phant")]
		phant,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:r")]
		r,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:rad")]
		rad,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:sPre")]
		sPre,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:sSub")]
		sSub,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:sSubSup")]
		sSubSup,
		[XmlEnum("http://schemas.openxmlformats.org/officeDocument/2006/math:sSup")]
		sSup,
		bookmarkEnd,
		bookmarkStart,
		commentRangeEnd,
		commentRangeStart,
		customXml,
		customXmlDelRangeEnd,
		customXmlDelRangeStart,
		customXmlInsRangeEnd,
		customXmlInsRangeStart,
		customXmlMoveFromRangeEnd,
		customXmlMoveFromRangeStart,
		customXmlMoveToRangeEnd,
		customXmlMoveToRangeStart,
		del,
		ins,
		moveFrom,
		moveFromRangeEnd,
		moveFromRangeStart,
		moveTo,
		moveToRangeEnd,
		moveToRangeStart,
		permEnd,
		permStart,
		proofErr,
		[XmlEnum("r")]
		r1,
		sdt,
		smartTag
	}
}
